--create table product_type (id bigint generated by default as identity (start with 1), description varchar(255), name varchar(255), primary key (id));
--create table product (id bigint generated by default as identity (start with 1), color varchar(255), description varchar(255), name varchar(255), product_type_id bigint, primary key (id));

INSERT INTO product_type(description, name) VALUES ('Plecaki', 'Plecaki');
INSERT INTO product_type(description, name) VALUES ('Namioty', 'Namioty');

INSERT INTO product(color, description, name, product_type_id) VALUES ('czerwony', 'Plecak 1', 'Plecak 1', 1);
INSERT INTO product(color, description, name, product_type_id) VALUES ('niebieski', 'Plecak 2', 'Plecak 2', 1);
INSERT INTO product(color, description, name, product_type_id) VALUES ('zielony', 'Namiot 2', 'Namiot 2', 2);