//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralWebService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCALIZATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOCALIZATION()
        {
            this.STORE = new HashSet<STORE>();
        }
    
        public int ID { get; set; }
        public string COUNTRY { get; set; }
        public string CITY { get; set; }
        public string STREET { get; set; }
        public int NUMBER { get; set; }
        public string POSTALCODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE> STORE { get; set; }
    }
}
